### ISSUE TITLE
What licensing is your project?

### ISSUE THREAD

**Issue by norlesh** [tinnywang/rubiks-cube#4]
Was looking at your code as a possible starting point for a project but could not find any reference to a licensing text anywhere and according to github [here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

which means anyone wanting to fork from your code is not legally aloud to do anything further with it, sort of muting the point of making the repository public.

**Comment by blonkm** [comment]
I got a notification of this and assumed it was for my project, but now I see it was for Tinny Wangs. Anyway, I asked her for permission. I think there are a lot of GitHub repositories where people just didn't bother with adding a license, but would have no problems with it. I'll let Tinny decide then what she wants to do. I'd prefer an MIT license.

**Comment by tinnywang** [comment]
Hi @norlesh, sorry for the delayed response. I've added the MIT license in https://github.com/tinnywang/rubiks-cube/commit/0b3365cfd896f81c85b6b99e6f695ad2382f8b43.
